---
driver:
  name: rackspace
  rackspace_username: <%= ENV['RACKSPACE_USERNAME'] %>
  rackspace_api_key: <%= ENV['RACKSPACE_API_KEY'] %>
  rackspace_region: 'lon'
  flavor_id: 'performance1-8'
  privileged: true
  require_chef_omnibus: 12.5.1

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    data_bags_path: "test/integration/mysql/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/mysql/data_bag_key"
    run_list:
      - recipe[iptables]
      - recipe[openssh::iptables]
      - recipe[redmine2]
      - recipe[redmine2::iptables]
    attributes:
      redmine:
        host: redmine.dev
        db:
          type: sqlite
        ssl_data_bag_name: redmine_example_com
  - name: mysql
    data_bags_path: "test/integration/mysql/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/mysql/data_bag_key"
    run_list:
      - recipe[iptables]
      - recipe[openssh::iptables]
      - recipe[redmine2]
      - recipe[redmine2::iptables]
    attributes:
      redmine:
        host: redmine.dev
        db:
          type: mysql
        ssl_data_bag_name: redmine_example_com
      mysql:
        server_root_password: q654321
        server_repl_password: q654321
        server_debian_password: q654321
  - name: postgresql
    run_list:
      - recipe[apt]
      - recipe[build-essential::default]
      - recipe[iptables]
      - recipe[openssh::iptables]
      - recipe[postgresql::server]
      - recipe[redmine2]
      - recipe[redmine2::iptables]
    attributes:
      apt:
        compile_time_update: true
        repository_uri: "http://uk.archive.ubuntu.com/ubuntu/"
      redmine:
        host: redmine.dev
        db:
          type: postgresql
        plugins:
          name: 'redmine_helpdesk'
          type: 'git'
          source: 'https://github.com/jfqd/redmine_helpdesk'
      postgresql:
        password:
          postgres: q654321
      build_essential:
        compiletime: true
